apiVersion: mq.aws.crossplane.io/v1alpha1
kind: Broker
metadata:
  name: test-rabbitmq
spec:
  deletionPolicy: Delete
  forProvider:
    region: eu-central-1
    engineType: RabbitMQ
    engineVersion: 3.8.11
    autoMinorVersionUpgrade: true
    hostInstanceType: mq.t3.micro
    deploymentMode: SINGLE_INSTANCE
    encryptionOptions:
      useAWSOwnedKey: true
    publiclyAccessible: true
    subnetIDs:
      - subnet-7c745915
    securityGroups:
      - sg-0a4c5663
    users: 
      - username: rabbitmq-admin
        consoleAccess: true
        passwordSecretRef:
          key: password
          name: test-rabbitmq-admin
          namespace: crossplane-system
  writeConnectionSecretToRef:
    name: test-rabbitmq
    namespace: default
  providerConfigRef:
    name: providerconfig-aws